# -*- coding: utf-8 -*-
"""BMI Calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16S3G7-cNfCk-sQr6su4qv-lijgmxr76r

The Body Mass Index or BMI is calculated from weight and height of a Person.
"""

Height=float(input("Enter your height in centimeters:  "))
Weight=float(input("Enter your weight in kg:  "))
Height=Height/100
BMI=Weight/(Height*Height)
print("Your body mass index is : ",BMI)
if(BMI>0):
  if(BMI<=16):
    print("You are severely underweight")
  elif(BMI<=18.5):
    print("You are underweight")
  elif(BMI<=25):
    print("You are healthy")
  elif(BMI<=30):
    print("You are overweight")
  else : print("You are severely underweight")
else : ("Enter valid details")